//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignment_4_12
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_
    {
        public int use_id { get; set; }
        public string use_name { get; set; }
        public string use_age { get; set; }
        public string use_gender { get; set; }
        public string use_phon { get; set; }
        public string use_city { get; set; }
        public string use_pass { get; set; }
    }
}
